// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msxmrsjtyzifelcqaney.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zeG1yc2p0eXppZmVsY3FhbmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTIyNTksImV4cCI6MjA2MDU2ODI1OX0.o8CFnbYdGDRvLuBpuasXV1Pw9Mjx_l5YFLPeOqdHCPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);